In [2]:
import pandas as pd
import numpy as np

In [8]:
# Get app data
df_clean = pd.read_csv("https://s3-eu-west-1.amazonaws.com/ai-hack-q3-orion/datasets/AI_Hackathon_Clean_Data.csv")

In [9]:
df_clean.head()

,Attendance_Percent,Course ID,Age,Gender,Income,Education,Promise Zone?,Primary Interest In Course,Hours Coded,How Many Hours A Week Can You Commit To Class,Hacker Rank Score,Completed?
0,0.846154,77,45,Male,"$40,000 - $50,000",Master's,0,Interested in seeking an apprenticeship/job in...,6-50,21-40,9.333333,0
1,0.142857,111,48,Female,"$40,000 - $50,000",High school or GED,0,Interested in seeking an apprenticeship/job in...,0-5,11-20,8.000000,0
2,0.269231,137,44,Male,"Less than $5,000",Bachelor's,0,Interested in seeking an apprenticeship/job in...,6-50,40+,9.333333,1
3,0.076923,125,30,Female,"$30,000 - $40,000",Associate's,1,Interested in seeking an apprenticeship/job in...,6-50,21-40,6.000000,0
4,0.730769,137,31,Male,"$40,000 - $50,000",Bachelor's,0,Interested in seeking an apprenticeship/job in...,0-5,21-40,4.666667,1

pd.get_dummies(df_clean,prefix=['Course ID', 'Gender', 'Income', 'Education', Primary Interest In Course', 'Hours Coded', 'How Many Hours A Week Can You Commit To Class'])

In [18]:
one_hot_encoded_df = pd.get_dummies(df_clean,prefix=[ 'Gender', 'Income', 'Education', 'Primary Interest In Course', 'Hours Coded', 'How Many Hours A Week Can You Commit To Class'])

In [19]:
one_hot_encoded_df.drop(axis=1, columns=['Course ID'])

,Attendance_Percent,Age,Promise Zone?,Hacker Rank Score,Completed?,Gender_Female,Gender_Male,Gender_Other,Gender_Prefer not to answer,"Income_$10,000 - $20,000",...,Primary Interest In Course_Professional development for my current job,Hours Coded_0-5,Hours Coded_250+,Hours Coded_51-250,Hours Coded_6-50,How Many Hours A Week Can You Commit To Class_0-5,How Many Hours A Week Can You Commit To Class_11-20,How Many Hours A Week Can You Commit To Class_21-40,How Many Hours A Week Can You Commit To Class_40+,How Many Hours A Week Can You Commit To Class_6-10
0,0.846154,45,0,9.333333,0,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1,0.142857,48,0,8.000000,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2,0.269231,44,0,9.333333,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3,0.076923,30,1,6.000000,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
4,0.730769,31,0,4.666667,1,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
5,0.240000,37,1,4.000000,0,1,0,0,0,1,...,0,0,1,0,0,0,0,0,1,0
6,0.346154,30,0,6.666667,1,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
7,0.825000,37,0,10.000000,1,1,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
8,0.750000,38,0,10.000000,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
9,1.000000,36,0,9.333333,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
10,0.974359,19,0,4.666667,1,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
11,0.846154,35,0,6.000000,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
12,0.192308,31,0,8.666667,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
13,0.875000,34,0,7.333333,0,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
14,0.115385,26,0,8.666667,0,0,1,0,0,1,...,0,1,0,0,0,0,0,1,0,0
15,0.450000,26,0,9.333333,1,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
16,0.692308,19,0,8.000000,0,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
17,0.375000,29,0,6.666667,1,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0
18,0.923077,36,0,7.333333,1,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,1
19,0.650000,23,0,6.000000,1,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
20,0.875000,25,0,9.333333,1,0,1,0,0,1,...,0,1,0,0,0,0,1,0,0,0
21,0.897436,26,1,8.666667,1,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
22,0.800000,29,0,9.333333,1,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
23,0.200000,52,0,4.000000,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
24,0.346154,26,1,0.666667,0,0,1,0,0,0,...,1,0,0,0,1,0,1,0,0,0
25,0.875000,41,0,8.666667,1,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
26,0.925000,29,0,8.666667,1,1,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
27,0.692308,31,0,6.666667,1,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
28,0.964286,29,0,6.666667,1,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
29,0.871795,29,0,9.333333,1,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1504,0.794872,30,0,9.333333,1,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,0
1505,0.675000,33,0,8.000000,1,1,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
1506,0.846154,33,0,8.666667,1,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
1507,0.800000,38,0,6.000000,0,1,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
1508,0.871795,35,0,7.333333,1,1,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1509,0.346154,22,0,6.666667,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1510,0.825000,30,1,6.000000,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
1511,0.897436,24,0,7.333333,1,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1512,0.240000,30,0,8.000000,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0
1513,0.153846,24,0,6.666667,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1514,0.512821,27,0,8.666667,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1515,0.423077,34,0,4.666667,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1516,0.440000,47,0,10.000000,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
1517,0.615385,53,0,8.000000,1,1,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
1518,0.948718,41,0,4.000000,1,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1519,0.607143,17,0,10.000000,1,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0
1520,0.269231,41,0,8.666667,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
1521,0.600000,29,0,8.000000,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1522,0.153846,59,1,2.666667,0,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1523,0.550000,29,0,7.333333,0,0,1,0,0,0,...,1,0,0,1,0,0,1,0,0,0
1524,0.153846,35,0,7.333333,0,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1525,0.975000,26,0,8.000000,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1526,0.550000,35,0,9.333333,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1527,0.500000,44,0,8.000000,0,1,0,0,0,1,...,0,0,0,0,1,0,0,1,0,0
1528,0.743590,30,0,8.000000,1,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
1529,0.846154,30,0,6.666667,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1530,0.961538,54,0,8.000000,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
1531,0.653846,20,0,6.666667,0,0,1,0,0,1,...,0,0,0,1,0,0,0,1,0,0
1532,0.346154,48,0,9.333333,0,0,1,0,0,1,...,0,0,0,0,1,0,0,1,0,0
1533,0.269231,26,0,4.666667,0,0,1,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [26]:
one_hot_encoded_df.to_csv('final_clean_orion.csv', sep=',', encoding='utf-8', index=False)